CSE_VIDEO_LIBRARY = [
    {
        "youtube_id": "8mAITcNt710",
        "title": "Harvard CS50 - Full Computer Science University Course",
        "channel": "freeCodeCamp.org",
        "subject": "Computer Science Fundamentals",
        "duration": "25h",
        "level": "Beginner",
        "topics": ["CS basics", "C", "algorithms", "memory", "Python", "SQL", "web"],
    },
    {
        "youtube_id": "RBSGKlAvoiM",
        "title": "Data Structures Easy to Advanced Course",
        "channel": "freeCodeCamp.org",
        "subject": "Data Structures",
        "duration": "8h",
        "level": "Intermediate",
        "topics": ["arrays", "linked lists", "stacks", "queues", "trees", "graphs", "hash tables"],
    },
    {
        "youtube_id": "8hly31xKli0",
        "title": "Algorithms and Data Structures Tutorial",
        "channel": "freeCodeCamp.org",
        "subject": "Algorithms",
        "duration": "6h",
        "level": "Beginner",
        "topics": ["Big O", "sorting", "searching", "recursion", "dynamic programming"],
    },
    {
        "youtube_id": "yK1uBHPdp30",
        "title": "Operating Systems - Full Course",
        "channel": "freeCodeCamp.org",
        "subject": "Operating Systems",
        "duration": "24h",
        "level": "Intermediate",
        "topics": ["processes", "threads", "scheduling", "memory", "paging", "deadlocks", "filesystems"],
    },
    {
        "youtube_id": "HXV3zeQKqGY",
        "title": "SQL Tutorial - Full Database Course",
        "channel": "freeCodeCamp.org",
        "subject": "DBMS",
        "duration": "4h",
        "level": "Beginner",
        "topics": ["SQL", "tables", "queries", "joins", "database design", "normalization"],
    },
    {
        "youtube_id": "qiQR5rTSshw",
        "title": "Computer Networking Course",
        "channel": "freeCodeCamp.org",
        "subject": "Computer Networks",
        "duration": "9h",
        "level": "Beginner",
        "topics": ["OSI model", "TCP/IP", "routing", "switching", "DNS", "HTTP"],
    },
    {
        "youtube_id": "F2FmTdLtb_4",
        "title": "System Design for Beginners",
        "channel": "freeCodeCamp.org",
        "subject": "System Design",
        "duration": "2h",
        "level": "Intermediate",
        "topics": ["scalability", "load balancing", "caching", "databases", "APIs"],
    },
    {
        "youtube_id": "i_LwzRVP7bg",
        "title": "Machine Learning for Everybody",
        "channel": "freeCodeCamp.org",
        "subject": "Machine Learning",
        "duration": "4h",
        "level": "Beginner",
        "topics": ["regression", "classification", "neural networks", "TensorFlow"],
    },
    {
        "youtube_id": "U_P23SqJaDc",
        "title": "Cyber Security Full Course for Beginners",
        "channel": "freeCodeCamp.org",
        "subject": "Cyber Security",
        "duration": "4h",
        "level": "Beginner",
        "topics": ["security basics", "network security", "web security", "threats"],
    },
    {
        "youtube_id": "vLnPwxZdW4Y",
        "title": "C++ Tutorial for Beginners - Full Course",
        "channel": "freeCodeCamp.org",
        "subject": "Programming",
        "duration": "4h",
        "level": "Beginner",
        "topics": ["C++", "variables", "functions", "classes", "pointers"],
    },
    {
        "youtube_id": "eWRfhZUzrAc",
        "title": "Python for Beginners - Full Course",
        "channel": "freeCodeCamp.org",
        "subject": "Programming",
        "duration": "4h",
        "level": "Beginner",
        "topics": ["Python", "variables", "functions", "classes", "files"],
    },
    {
        "youtube_id": "xk4_1vDrzzo",
        "title": "Java Full Course for Beginners",
        "channel": "Bro Code",
        "subject": "Programming",
        "duration": "12h",
        "level": "Beginner",
        "topics": ["Java", "OOP", "classes", "inheritance", "exceptions"],
    },
    {
        "youtube_id": "G3e-cpL7ofc",
        "title": "HTML and CSS Full Course",
        "channel": "SuperSimpleDev",
        "subject": "Web Development",
        "duration": "6h",
        "level": "Beginner",
        "topics": ["HTML", "CSS", "layouts", "responsive design", "frontend"],
    },
    {
        "youtube_id": "EerdGm-ehJQ",
        "title": "JavaScript Full Course",
        "channel": "SuperSimpleDev",
        "subject": "Web Development",
        "duration": "12h",
        "level": "Beginner",
        "topics": ["JavaScript", "DOM", "events", "arrays", "objects"],
    },
    {
        "youtube_id": "bMknfKXIFA8",
        "title": "React JS Full Course for Beginners",
        "channel": "freeCodeCamp.org",
        "subject": "Web Development",
        "duration": "12h",
        "level": "Intermediate",
        "topics": ["React", "components", "state", "hooks", "frontend"],
    },
    {
        "youtube_id": "Oe421EPjeBE",
        "title": "Node.js and Express.js Full Course",
        "channel": "freeCodeCamp.org",
        "subject": "Web Development",
        "duration": "8h",
        "level": "Intermediate",
        "topics": ["Node.js", "Express", "REST API", "backend", "middleware"],
    },
    {
        "youtube_id": "RGOj5yH7evk",
        "title": "Git and GitHub for Beginners",
        "channel": "freeCodeCamp.org",
        "subject": "Developer Tools",
        "duration": "1h",
        "level": "Beginner",
        "topics": ["Git", "GitHub", "version control", "branches", "pull requests"],
    },
]
